version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: lucrafood
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: lucrafood
    ports:
      - "5432:5432"
